-- ACTIVATE VECTOR EXTENSION (Run this first!)
create extension if not exists vector;
-- 1. KNOWLEDGE BASE (Norms, POT, Documents)
-- Stores official knowledge fragments.
create table public.knowledge_base (
    id bigint generated by default as identity primary key,
    content text not null,
    metadata jsonb default '{}'::jsonb,
    -- e.g. { source: "POT 2024", page: 45, article: "Art 5" }
    embedding vector(768) -- Gemini Text Embedding 004 dimension
);
-- 2. VALUATION MEMORY (Past Appraisals)
-- Stores summaries of completed valuations for comparison.
create table public.valuation_memory (
    id bigint generated by default as identity primary key,
    solicitud_id bigint references public.solicitudes(id),
    summary_text text not null,
    -- "Apartamento en Chicó, 80m2, remodelado, precio mercado 500M"
    valuation_price numeric,
    metadata jsonb default '{}'::jsonb,
    -- e.g. { location: "Chicó", area: 80, year: 2024 }
    embedding vector(768)
);
-- 3. SEARCH FUNCTIONS (RPC)
-- Function to search Knowledge Base
create or replace function match_knowledge (
        query_embedding vector(768),
        match_threshold float,
        match_count int
    ) returns table (
        id bigint,
        content text,
        metadata jsonb,
        similarity float
    ) language plpgsql as $$ begin return query
select kb.id,
    kb.content,
    kb.metadata,
    1 - (kb.embedding <=> query_embedding) as similarity
from knowledge_base kb
where 1 - (kb.embedding <=> query_embedding) > match_threshold
order by similarity desc
limit match_count;
end;
$$;
-- Function to search Valuation Memory (Comparables)
create or replace function match_valuations (
        query_embedding vector(768),
        match_threshold float,
        match_count int
    ) returns table (
        id bigint,
        solicitud_id bigint,
        summary_text text,
        valuation_price numeric,
        metadata jsonb,
        similarity float
    ) language plpgsql as $$ begin return query
select vm.id,
    vm.solicitud_id,
    vm.summary_text,
    vm.valuation_price,
    vm.metadata,
    1 - (vm.embedding <=> query_embedding) as similarity
from valuation_memory vm
where 1 - (vm.embedding <=> query_embedding) > match_threshold
order by similarity desc
limit match_count;
end;
$$;
-- RLS POLICIES (Security)
alter table public.knowledge_base enable row level security;
alter table public.valuation_memory enable row level security;
-- Allow READ to authenticated users (JanIA operating as user)
create policy "Allow read access to authenticated users" on public.knowledge_base for
select to authenticated using (true);
create policy "Allow read access to authenticated users valuations" on public.valuation_memory for
select to authenticated using (true);
-- Allow INSERT to authenticated users (for JanIA to learn)
create policy "Allow insert access to authenticated users" on public.knowledge_base for
insert to authenticated with check (true);
create policy "Allow insert access to authenticated users valuations" on public.valuation_memory for
insert to authenticated with check (true);